---
title: '2021-05-04'
author: "ses"
date: "5/4/2021"
output: html_document
---

# Vorbereitung

```{r}
library(tidyverse)
```



# Daten laden

```{r}
data_url <- "https://raw.githubusercontent.com/sebastiansauer/willingness-vaccination-covid19/main/data/d3.csv"

d3 <- read_csv(data_url)  # wohnt im tidyverse
```



```{r}
d3 %>% 
  summarise(willingness = mean(willingness, na.rm = TRUE))
```


# Test


```{r}
d3 %>%
  drop_na(age, willingness, health) %>% 
  summarise(
    cor_willingness_age = cor(age, willingness),
    cor_willingness_health = cor(health, willingness))
```



# Schnörkel


```{r}
library(hrbrthemes)

d3_sum <-
  d3 %>% 
  summarise(willingness_avg = mean(willingness, na.rm = T),
            cases_avg = mean(cases, na.rm = T))

d3 %>% 
  mutate(willingness = willingness * 10) %>% 
  mutate(sex_na = is.na(sex)) %>% 
  ggplot(aes(x = cases, 
             y = willingness)) +
  geom_jitter(alpha = .7, aes(color = sex)) +
  labs(title = "Impfbereitschaft in Abhängigkeit",
       subtitle = "der persönlich bekannten Covid19-Fälle",
       color = "Geschlecht",
       caption = "Umfrage unter n=160 Studierenden, Datum: April 2021") +
  scale_color_viridis_d() +
  theme_ipsum_tw() +
  theme(legend.position = "bottom") +
  geom_hline(yintercept= 8.1*10, linetype = "dashed") +
  geom_label(x = 50, y = 81, label =  "MW",
            hjust = 1)
```


```{r}
d3 %>% 
  ggplot(aes(x = sex, y = willingness)) +
  geom_boxplot() 
```



