---
title: '2021-05-06'
author: "ses"
date: "5/6/2021"
output: html_document
---


# Setup 

```{r}
library(tidyverse)
```



# Datensatz `flights`

```{r}
library(nycflights13)
data(flights)
```

Use what you’ve learned to improve the visualisation of the *scheduled departure times* of *cancelled vs. non-cancelled flights*.



# Aufgabe

Ergänzen Sie eine Visualisierung des Medians!

```{r}
p1 <- flights %>% 
  mutate(is_cancelled = is.na(dep_time)) %>% 
  ggplot() +
  aes(y = sched_dep_time, x = is_cancelled) +
  geom_violin()

p1
```


Zusammenfassungen berechnen:

```{r}
flights_summary <- 
  flights %>% 
  mutate(is_cancelled = is.na(dep_time)) %>% 
  group_by(is_cancelled) %>% 
  summarise(sched_dep_time_median = median(sched_dep_time),
            sched_dep_time_iqr = IQR(sched_dep_time))
```


```{r}
ggplot(flights_summary) +
  aes(x = is_cancelled, y = sched_dep_time_median) +
  geom_point(size = 4, color = "red")
```



```{r}
p2 <- p1 +
  geom_point(data = flights_summary,
             aes(y = sched_dep_time_median),
             size = 5,
             color = "red") 

p2
```



```{r}
flights %>% 
  mutate(is_cancelled = is.na(dep_time)) %>% 
  ggplot() +
  aes(x = is_cancelled) +
  geom_violin(aes(y = sched_dep_time)) + 
  geom_errorbar(data = flights_summary,
                aes(
                  ymax = sched_dep_time_median + 
                      sched_dep_time_iqr/2,
                    ymin = sched_dep_time_median - 
                      sched_dep_time_iqr/2 ),
                width = .1,
                color = "grey60"
                ) +
  geom_point(data = flights_summary,
             aes(y = sched_dep_time_median),
             size = 5,
             color = "red") 
```




# Daten laden

```{r}
data_url <- "https://raw.githubusercontent.com/sebastiansauer/willingness-vaccination-covid19/main/data/d3.csv"

d3 <- read_csv(data_url)  # wohnt im tidyverse
```




# Schnörkel

```{r}
wip_data <- read_csv("../../data/WiP/WB-WiP.csv")
```




