

Hallo, ich bin eine Markdown-Datei.


# Pakete laden

```{r}
library(tidyverse)  # auch für CSV-Import
library(tidytext)
library(janeaustenr)
library(dplyr)
library(stringr)
library(readxl)  # für XLS(X)-Import
library(gutenbergr)
library(scales)  # Achsen mit Prozentwerten beschriften ("%")
```



```{r}
text <- c("Because I could not stop for Death -",
          "He kindly stopped for me -",
          "The Carriage held but just Ourselves -",
          "and Immortality")



v <- 1:100
v
text

```



# Abschnitt 1.3 in "Tidy Text"


<https://www.tidytextmining.com/tidytext.html#the-unnest_tokens-function>


```{r}

original_books <-
  austen_books() %>% 
  group_by(book) %>%
  mutate(linenumber = row_number()) %>% 
  ungroup()
```


```{r}
tidy_books <- original_books %>%
  unnest_tokens(word, text)

```


# Wichtige Berechnung


```{r}
1+1
```


Bla blaa bla



# Interviewdaten aus XLSX importieren


```{r}
text_ex_df <-
  read_xlsx("text-example.xlsx")
```


# Bücher aus Projekt Gutenberg importieren


```{r}
faust1 <- gutenberg_download(2229)
```

```{r}
hgwells <- gutenberg_download(c(35, 36, 5230, 159))

tidy_hgwells <- hgwells %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```



```{r}
bronte <- gutenberg_download(c(1260, 768, 969, 9182, 767))

tidy_bronte <- 
  bronte %>%
  unnest_tokens(word, text) %>%
  anti_join(stop_words)
```



```{r}
frequency <- 
  bind_rows(mutate(tidy_bronte, author = "Brontë Sisters"),
                       mutate(tidy_hgwells, author = "H.G. Wells"), 
                       mutate(tidy_books, author = "Jane Austen")) %>% 
  mutate(word = str_extract(word, "[a-z']+")) %>%  # # nimm alle Buchstaben und das Apostroph, sonst n
  count(author, word) %>% 
  group_by(author) %>%
  mutate(proportion = n / sum(n)) %>% 
  select(-n) %>% 
  pivot_wider(names_from = author, values_from = proportion) %>%
  pivot_longer(`Brontë Sisters`:`H.G. Wells`,
               names_to = "author", values_to = "proportion")
```



```{r}
# expect a warning about rows with missing values being removed
ggplot(frequency, aes(x = proportion, y = `Jane Austen`, 
                      color = abs(`Jane Austen` - proportion))) +
  geom_abline(color = "gray40", lty = 2) +
  geom_jitter(alpha = 0.1, size = 2.5, width = 0.3, height = 0.3) +
  geom_text(aes(label = word), check_overlap = TRUE, vjust = 1.5) +
  scale_x_log10(labels = percent_format()) +
  scale_y_log10(labels = percent_format()) +
  scale_color_gradient(limits = c(0, 0.001), 
                       low = "darkslategray4", high = "gray75") +
  facet_wrap(~author, ncol = 2) +
  theme(legend.position="none") +
  labs(y = "Jane Austen", x = NULL)
```

